Convert to Ruby 2.5/Rails 5.2

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,47 +1,36 @@
-#!/bin/sh
+#!/usr/bin/env ruby
+require 'fileutils'
+include FileUtils
 
-# Set up Rails app. Run this script immediately after cloning the codebase.
-# https://github.com/thoughtbot/guides/tree/master/protocol
+# path to your application root.
+APP_ROOT = File.expand_path('..', __dir__)
 
-# Exit if any subcommand fails
-set -e
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-# Set up Ruby dependencies via Bundler
-gem install bundler --conservative
-bundle check || bundle install
+chdir APP_ROOT do
+  # This script is a starting point to setup your application.
+  # Add necessary setup steps to this file.
 
-# Set up database and add any development seed data
-bin/rails dev:prime
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check') || system!('bundle install')
 
-if [ ! -d .git/safe ] && echo $PATH | grep .git/safe > /dev/null; then
-  echo "-----------------------------------------------------------------------"
-  echo
-  echo "-> When you trust this repo, remember to run: mkdir -p .git/safe"
-  echo
-fi
+  # Install JavaScript dependencies if using Yarn
+  # system('bin/yarn')
 
-# Only if this isn't CI
-# if [ -z "$CI" ]; then
-# fi
+  # puts "\n== Copying sample files =="
+  # unless File.exist?('config/database.yml')
+  #   cp 'config/database.yml.sample', 'config/database.yml'
+  # end
 
-if heroku join --app echo-ruby-staging > /dev/null 2>&1; then
-  git remote add staging git@heroku.com:echo-ruby-staging.git || true
-  printf 'You are a collaborator on the "echo-ruby-staging" Heroku app
-'
-else
-  printf 'Ask for access to the "echo-ruby-staging" Heroku app
-'
-fi
+  puts "\n== Preparing database =="
+  system! 'bin/rails db:setup'
 
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
 
-if heroku join --app echo-ruby-production > /dev/null 2>&1; then
-  git remote add production git@heroku.com:echo-ruby-production.git || true
-  printf 'You are a collaborator on the "echo-ruby-production" Heroku app
-'
-else
-  printf 'Ask for access to the "echo-ruby-production" Heroku app
-'
-fi
-
-
-git config heroku.remote staging
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
